TI-14 <list of countries fetching from BE and displaying done >
Nick2603/your_dream_holidays pull request #10
Opened 2022-06-02 10:39 UTC by Nick2603

2022-06-02 10:40 UTC, Nick2603 commented
![image](https://user-images.githubusercontent.com/87815899/171612371-f74abe05-d7ca-4ba1-a5b1-7e27e5ba9286.png)

2022-06-03 06:56 UTC, Hopchenko requested changes

2022-06-03 06:56 UTC, Hopchenko commented on src/components/CountrySelect/CountrySelect.tsx
> +  const getCountryList = () => {
https://redux.js.org/tutorials/essentials/part-5-async-logic

2022-06-07 08:34 UTC, Hopchenko approved these changes
Great work!

2022-06-07 08:37 UTC, merged